/*---------------------------------------------------------------------------------
    PIZZA SNAKE - SNES
---------------------------------------------------------------------------------*/
#include <snes.h>
#include <string.h>

#include "trig_table.h"
#include "tiles_charmap.h"
#include "sprite_tiles.h"

extern char gfxsprites, gfxsprites_end;
extern char palsprites, palsprites_end;
extern char gfxwalls, gfxwalls_end;
extern char palwalls, palwalls_end;

//---------------------------------------------------------------------------------
// Arena bounds (pixel space)
#define ARENA_LEFT   14
#define ARENA_RIGHT  242
#define ARENA_TOP    30
#define ARENA_BOTTOM 210

#define TRAILSIZE    1024
#define MAX_LEN      3000  /* effectively unlimited; baking removes the OAM ceiling */
#define SPRITE_WINDOW 55   /* most recent segments rendered as smooth sprites --
                               kept modest so per-frame sprite updates stay cheap;
                               everything beyond this is baked onto the BG layer */
#define SEG_SPACING  2
#define BAKE_STEP    1     /* sample the trail every frame for bake/erase
                               classification, finer than SEG_SPACING so
                               entry/exit points are captured precisely */
#define TURN_RATE    5
#define MOVESPEED    210   /* desired sub-pixel speed per frame, Q7 (128=1px), ~1.6px/frame */
#define SELF_SKIP    8
#define SELF_R       3     /* pixel radius, cheap abs-based check (thin body) */
#define PIZZA_R      6
#define OAM_PIZZA    0
#define OAM_HEAD     4
#define OAM_BODY0    8

#define ST_TITLE     0
#define ST_PLAYING   1
#define ST_GAMEOVER  2
#define ST_ENTERNAME 3
#define ST_HISCORES  4

#define NAME_LEN     3
#define NUM_SCORES   20

//---------------------------------------------------------------------------------
u16 blockmap[0x400];

s16 trailX[TRAILSIZE];
s16 trailY[TRAILSIZE];
u16 headIdx;

u8 angle;
s32 posX, posY; /* Q7 fixed point (scaled by 128) */
u16 curLen;
u16 score;
u16 pizzaX, pizzaY;
u16 pizzaValue;
u8 pizzaBig;
u8 gameState;
u16 randSeed;
u16 pad0;
u8 hudDirty;
u16 oamHighWater;
u16 snakeAge;
u16 nextBakeSample;
u16 nextEraseSample;
u16 lastErasedCell;

/* Baked background body: every touch point the path makes with a tile
   boundary is represented as (edge, along) -- which of the 4 edges, and
   which of the 8 pixel positions along it -- packed into a single 0-31
   index via POINT(edge,along). This is deliberately NOT a raw (x,y)
   pixel: a point sitting exactly at a tile corner is genuinely ambiguous
   as a bare coordinate (it's simultaneously "column 0" and "row 0"), and
   the two readings need different stub directions when rendered. Keeping
   the edge explicit removes the ambiguity at its source instead of
   re-guessing it later.

   TAIL_CONNECTOR_TILE[a*32+b] (generated by gen_tiles.py) maps any pair
   of touch points straight to a background tile value (index + flip
   bits) -- a plain lookup, no runtime branching on cases.

   Both cells sharing a boundary must reference the EXACT same touch
   point for the connection to render seamlessly, so whichever cell is
   entered borrows its along-coordinate from the cell being exited (see
   stepSnake): a raw per-frame sample lands within ~2px of the boundary
   it just crossed, not exactly on it, so using each side's own sample
   independently can disagree by a pixel and leave a hairline seam. A
   diagonal step (the path clips a tile corner between two samples, never
   landing in either cell that shares a full edge with both neighbours)
   is resolved by interpolating the straight line between the last two
   samples to find which of the two candidate cells it actually passed
   through, and synthesizing that skipped cell too. */
#define POINT(edge, along) ((u8)((edge) * 8 + (along)))
u16 pendingCell;
u8 pendingEntryPoint;
u16 prevBakeX, prevBakeY;

#define MAX_DIRTY 16
u16 dirtyCell[MAX_DIRTY];
u8 dirtyCount;

char hiName[NAME_LEN + 1];
u8 nameLetters[NAME_LEN];
u8 nameCursor;

u16 hsScore[NUM_SCORES];
char hsName[NUM_SCORES][NAME_LEN + 1];

//---------------------------------------------------------------------------------
u16 nextRand(void)
{
    /* simple LCG, good enough for pizza placement */
    randSeed = randSeed * 25173 + 13849;
    return randSeed;
}

//---------------------------------------------------------------------------------
void clearMapRegion(u16 startCell, u16 count, u16 tile)
{
    u16 i;
    for (i = 0; i < count; i++)
        blockmap[startCell + i] = tile;
}

//---------------------------------------------------------------------------------
void writeText(u16 col, u16 row, const char *st)
{
    u16 p = row * 32 + col;
    u8 c;
    while ((c = *st))
    {
        blockmap[p] = asciiTile[c & 0x7F];
        p++;
        st++;
    }
}

//---------------------------------------------------------------------------------
void writeNum(u16 col, u16 row, u16 num, u8 len)
{
    u16 p = row * 32 + col + len - 1;
    u8 i;
    for (i = 0; i < len; i++)
    {
        u8 figure = num % 10;
        blockmap[p] = asciiTile[figure + '0'];
        num /= 10;
        p--;
    }
}

//---------------------------------------------------------------------------------
void drawWalls(void)
{
    u8 x, y;
    clearMapRegion(0, 0x400, TILE_BLANK);
    for (x = 0; x < 32; x++)
        blockmap[2 * 32 + x] = TILE_WALL;
    for (x = 0; x < 32; x++)
        blockmap[27 * 32 + x] = TILE_WALL;
    for (y = 3; y < 27; y++)
    {
        blockmap[y * 32 + 0] = TILE_WALL;
        blockmap[y * 32 + 31] = TILE_WALL;
    }
}

//---------------------------------------------------------------------------------
void hideAllSprites(void)
{
    u16 i;
    for (i = 0; i < 128; i++)
        oamSetVisible(i * 4, OBJ_HIDE);
    oamHighWater = 0;
}

//---------------------------------------------------------------------------------
void spawnPizza(void)
{
    u16 r;
    pizzaX = ARENA_LEFT + 8 + (nextRand() % (ARENA_RIGHT - ARENA_LEFT - 16));
    pizzaY = ARENA_TOP + 8 + (nextRand() % (ARENA_BOTTOM - ARENA_TOP - 16));

    r = nextRand() % 10;
    if (r < 3)
    {
        /* big pizza: rarer, worth more, grows more */
        pizzaBig = 1;
        pizzaValue = 20 + (nextRand() % 20); /* 20-39 */
        oamSetEx(OAM_PIZZA, OBJ_LARGE, OBJ_SHOW);
        oamSet(OAM_PIZZA, pizzaX - 8, pizzaY - 8, 2, 0, 0, SPR_PIZZA_BIG, 0);
    }
    else
    {
        pizzaBig = 0;
        pizzaValue = 5 + (nextRand() % 10); /* 5-14 */
        oamSetEx(OAM_PIZZA, OBJ_SMALL, OBJ_SHOW);
        oamSet(OAM_PIZZA, pizzaX - 4, pizzaY - 4, 2, 0, 0, SPR_PIZZA_SMALL, 0);
    }
}

//---------------------------------------------------------------------------------
void resetGame(void)
{
    u16 i;
    posX = ((s32)128) << 7;
    posY = ((s32)112) << 7;
    angle = 0;
    curLen = 10;
    score = 0;
    headIdx = 0;
    hudDirty = 1;
    snakeAge = 0;
    nextBakeSample = 0;
    nextEraseSample = 0;
    lastErasedCell = 0xFFFF;
    dirtyCount = 0;
    pendingCell = 0xFFFF;
    for (i = 0; i < TRAILSIZE; i++)
    {
        trailX[i] = 128;
        trailY[i] = 112;
    }
    drawWalls();
    hideAllSprites();
    oamHighWater = 2; /* oam #0 (pizza) and #1 (head) are managed separately below */
    oamSetEx(OAM_HEAD, OBJ_SMALL, OBJ_SHOW);
    oamSet(OAM_HEAD, (u16)(posX >> 7) - 4, (u16)(posY >> 7) - 4, 3, 0, 0, SPR_HEAD, 0);
    spawnPizza();
}

//---------------------------------------------------------------------------------
void drawHud(void)
{
    writeText(1, 0, "SCORE");
    writeNum(7, 0, score, 6);
    writeText(18, 0, "HI");
    if (hsScore[0])
        writeText(21, 0, hsName[0]);
    writeNum(25, 0, hsScore[0], 6);
}

//---------------------------------------------------------------------------------
void drawSprites(void)
{
    u16 i;
    u16 oamId;
    u16 hx, hy;
    u16 activeCount;
    u16 bodyCount;

    /* head: position only -- tile/attrs were set once in resetGame().
       Written directly into the OAM shadow buffer (auto-DMA'd at vblank by
       the library) instead of going through oamSetXY -- avoids a function
       call per sprite per frame, which matters once dozens of segments are
       being updated every single frame. */
    hx = (u16)(posX >> 7);
    hy = (u16)(posY >> 7);
    oamMemory[OAM_HEAD + 0] = (u8)(hx - 4);
    oamMemory[OAM_HEAD + 1] = (u8)(hy - 4);

    /* only the most recent SPRITE_WINDOW segments are rendered as sprites;
       older segments get permanently baked onto the BG layer in stepSnake(),
       which is how the snake can grow far past the 128-sprite hardware limit */
    bodyCount = curLen;
    if (bodyCount > SPRITE_WINDOW)
        bodyCount = SPRITE_WINDOW;

    /* newly active body slots: set tile/attr once (never changes again --
       a single fixed shape, so there's nothing to update per frame beyond
       position, and no risk of the flicker a per-frame-changing shape
       would cause) */
    activeCount = 2 + bodyCount;
    if (activeCount > oamHighWater)
    {
        for (i = oamHighWater; i < activeCount; i++)
        {
            oamSetEx(i * 4, OBJ_SMALL, OBJ_SHOW);
            oamMemory[i * 4 + 2] = SPR_BODY;
            oamMemory[i * 4 + 3] = OAM_ATTR(1, 0, 0, SPR_BODY, 0);
        }
        oamHighWater = activeCount;
    }

    /* every active body segment: cheap position-only update each frame */
    for (i = 0; i < bodyCount; i++)
    {
        u16 tIdx = (headIdx + TRAILSIZE - (u16)((i + 1) * SEG_SPACING)) % TRAILSIZE;
        oamId = OAM_BODY0 + i * 4;
        oamMemory[oamId + 0] = (u8)(trailX[tIdx] - 4);
        oamMemory[oamId + 1] = (u8)(trailY[tIdx] - 4);
    }
}

//---------------------------------------------------------------------------------
s32 abs32(s32 v)
{
    return (v < 0) ? -v : v;
}

//---------------------------------------------------------------------------------
s32 divRound(s32 num, s32 den)
{
    /* Round num/den to the nearest integer (ties away from zero) instead
       of truncating toward zero -- plain integer division here would bias
       the rare diagonal-interpolation case by up to a pixel, e.g. -1/-2
       truncates to 0 when the mathematically nearer answer is the same
       either way, but 103.5 truncates down to 103 instead of rounding to
       104. Doesn't affect whether two cells' touch points agree (both
       sides of a junction always use this same computed value), only how
       close that shared value lands to the true crossing point.
       Deliberately a real function, not a macro: num/den are often
       themselves multi-step expressions (see interpAlong), and a macro
       that mentions its arguments more than once would recompute those
       expressions repeatedly after expansion -- which is exactly what
       blew up 816-tcc's stack-temporary count enough to overflow the
       assembler's 8-bit stack-relative addressing here. */
    s32 aNum = abs32(num);
    s32 aDen = abs32(den);
    s32 mag = (aNum + aDen / 2) / aDen;
    return ((num < 0) == (den < 0)) ? mag : -mag;
}

u8 axisDir(u16 fromCell, u16 toCell)
{
    /* Which edge of fromCell is crossed to reach toCell (0=left,1=right,
       2=top,3=bottom) -- fromCell's EXIT edge, exact, no guessing.
       toCell's matching entry edge is always the opposite (XOR 1, since
       this encoding pairs 0<->1 and 2<->3). Returns 0xFF if the two cells
       aren't simple axis neighbours (the path clipped a corner and
       stepped diagonally between samples). */
    s16 dCol = (s16)(toCell % 32) - (s16)(fromCell % 32);
    s16 dRow = (s16)(toCell / 32) - (s16)(fromCell / 32);
    if (dCol == 1 && dRow == 0) return 1;  /* exits fromCell's right edge */
    if (dCol == -1 && dRow == 0) return 0; /* exits fromCell's left edge */
    if (dRow == 1 && dCol == 0) return 3;  /* exits fromCell's bottom edge */
    if (dRow == -1 && dCol == 0) return 2; /* exits fromCell's top edge */
    return 0xFF;
}

//---------------------------------------------------------------------------------
void finalizeTile(u16 cell, u8 entryPoint, u8 exitPoint)
{
    /* tailConnectorTile[] (generated by gen_tiles.py) already covers
       every one of the 32x32 possible touch-point combinations, so
       there's no case analysis left to do here -- just look up the tile
       that was pre-built for this exact pair. */
    blockmap[cell] = tailConnectorTile[(u16)entryPoint * 32 + exitPoint];
    if (dirtyCount < MAX_DIRTY)
        dirtyCell[dirtyCount++] = cell;
}

//---------------------------------------------------------------------------------
u8 bakeSimpleCrossing(u16 pendingCell, u8 pendingEntryPoint, u16 cell, u8 d, u8 localX, u8 localY)
{
    /* Simple axis crossing: borrow the along-edge coordinate from THIS
       sample (the cell being entered) for both cells' shared touch point.
       A raw sample lands within ~2px of the boundary it just crossed, not
       exactly on it, so using each side's own independent sample can
       disagree by a pixel and leave a hairline seam -- sharing one value
       guarantees both sides agree exactly. Returns the touch point the
       newly-entered cell should use as ITS entry. */
    u8 along = (d == 0 || d == 1) ? localY : localX;
    finalizeTile(pendingCell, pendingEntryPoint, POINT(d, along));
    return POINT(d ^ 1, along);
}

//---------------------------------------------------------------------------------
u8 interpAlong(u16 refCell, u8 d, s32 ax, s32 ay, s32 ddx, s32 ddy)
{
    /* Where the straight line from (ax,ay) to (ax+ddx,ay+ddy) crosses
       refCell's edge d, expressed as the local along-edge coordinate.
       Split out from bakeDiagonalCrossing (which needs this twice) purely
       to keep any single function's expression count -- and therefore its
       816-tcc stack-temporary usage -- small enough to fit an 8-bit
       stack-relative offset; see bakeDiagonalCrossing's comment. */
    s32 b;
    if (d == 0 || d == 1)
    {
        b = ((s32)(refCell % 32) + (d == 1 ? 1 : 0)) * 8;
        if (ddx == 0) return (u8)((u16)ay & 7);
        return (u8)((u16)(ay + divRound((b - ax) * ddy, ddx)) & 7);
    }
    b = ((s32)(refCell / 32) + (d == 3 ? 1 : 0)) * 8;
    if (ddy == 0) return (u8)((u16)ax & 7);
    return (u8)((u16)(ax + divRound((b - ay) * ddx, ddy)) & 7);
}

//---------------------------------------------------------------------------------
u16 diagonalMidCell(u16 pendingCell, u16 cell, s32 ax, s32 ay, s32 ddx, s32 ddy)
{
    /* Which of the two cells diagonally between pendingCell and cell the
       straight line between the last two samples actually clipped
       through -- split out for the same stack-frame-size reason as
       interpAlong above. */
    s16 dCol = (s16)(cell % 32) - (s16)(pendingCell % 32);
    s16 dRow = (s16)(cell / 32) - (s16)(pendingCell / 32);
    s32 colBoundary = ((s32)(pendingCell % 32) + (dCol > 0 ? 1 : 0)) * 8;
    s32 rowBoundary = ((s32)(pendingCell / 32) + (dRow > 0 ? 1 : 0)) * 8;
    s32 tCol = abs32(colBoundary - ax) * abs32(ddy);
    s32 tRow = abs32(rowBoundary - ay) * abs32(ddx);
    if (tCol < tRow)
        return (dCol > 0) ? (u16)(pendingCell + 1) : (u16)(pendingCell - 1);
    return (dRow > 0) ? (u16)(pendingCell + 32) : (u16)(pendingCell - 32);
}

//---------------------------------------------------------------------------------
u8 bakeDiagonalCrossing(u16 pendingCell, u8 pendingEntryPoint, u16 cell,
                         u16 prevX, u16 prevY, u16 curX, u16 curY)
{
    /* Diagonal: the path clipped a tile corner between the last sample and
       this one, skipping the cell that would normally share a full edge
       with both neighbours -- the two cells here only share a single
       corner pixel. Find which of the two candidate cells the straight
       line between the last two samples actually passed through, and
       bake that skipped cell too. The real work is split into
       diagonalMidCell()/interpAlong() above: 816-tcc allocates a stack
       slot per sub-expression rather than per C variable, so a function
       with this many nested computations in one body can overflow the
       8-bit stack-relative addressing the assembler needs -- keeping each
       function's own expression count small avoids that regardless of
       how much total work the whole crossing needs. */
    s32 ax = (s32)prevX, ay = (s32)prevY;
    s32 ddx = (s32)curX - ax, ddy = (s32)curY - ay;
    u16 midCell = diagonalMidCell(pendingCell, cell, ax, ay, ddx, ddy);
    u8 d1 = axisDir(pendingCell, midCell);
    u8 along1 = interpAlong(pendingCell, d1, ax, ay, ddx, ddy);
    u8 d2 = axisDir(midCell, cell);
    u8 along2 = interpAlong(midCell, d2, ax, ay, ddx, ddy);

    finalizeTile(pendingCell, pendingEntryPoint, POINT(d1, along1));
    finalizeTile(midCell, POINT(d1 ^ 1, along1), POINT(d2, along2));
    return POINT(d2 ^ 1, along2);
}

//---------------------------------------------------------------------------------
u8 bakeFirstCell(u8 localX, u8 localY)
{
    /* First cell ever baked: no previous cell to derive an exact touch
       point from, so fall back to whichever edge the raw sample is
       nearest -- a one-time approximation that only ever affects the very
       start of the baked trail. */
    u8 d0 = 0, best = localX, dd;
    dd = (u8)(7 - localX); if (dd < best) { best = dd; d0 = 1; }
    dd = localY;           if (dd < best) { best = dd; d0 = 2; }
    dd = (u8)(7 - localY); if (dd < best) { best = dd; d0 = 3; }
    return POINT(d0, (d0 == 0 || d0 == 1) ? localY : localX);
}

//---------------------------------------------------------------------------------
u8 stepSnake(void)
{
    s32 dx, dy;
    u16 hx, hy;
    u16 i;

    /* left/right reversed per player preference */
    if (pad0 & KEY_LEFT)
        angle += TURN_RATE;
    if (pad0 & KEY_RIGHT)
        angle -= TURN_RATE;

    dx = ((s32)cosTable[angle] * MOVESPEED) >> 7;
    dy = -(((s32)sinTable[angle] * MOVESPEED) >> 7);
    posX += dx;
    posY += dy;

    hx = (u16)(posX >> 7);
    hy = (u16)(posY >> 7);

    headIdx = (headIdx + 1) % TRAILSIZE;
    trailX[headIdx] = hx;
    trailY[headIdx] = hy;
    snakeAge++;

    if (hx < ARENA_LEFT || hx > ARENA_RIGHT || hy < ARENA_TOP || hy > ARENA_BOTTOM)
        return 1; /* wall death */

    /* Bake segments that have aged out of the sprite-rendering window onto
       the BG tilemap, and erase the oldest baked segment once it falls
       outside the snake's actual current length. Since the snake only grows
       via eating (not via distance travelled), the *total* body length must
       stay fixed at curLen -- without erasing, the baked tail would just
       accumulate the snake's entire lifetime path forever, which is wrong.

       Both cursors are kept pinned to "now" whenever they're not actively
       needed, rather than left frozen, so there is never a backlog to
       catch up on in one frame (which would either freeze the game for a
       long stretch, or -- once the backlog exceeds TRAILSIZE -- read
       positions already overwritten in the circular trail buffer and bake
       tiles at garbage locations). */
    {
        s32 bakeThreshold = (s32)snakeAge - (s32)SPRITE_WINDOW * SEG_SPACING;
        s32 eraseThreshold = (s32)snakeAge - (s32)curLen * SEG_SPACING;

        if (curLen <= SPRITE_WINDOW)
        {
            nextBakeSample = (bakeThreshold > 0) ? (u16)bakeThreshold : 0;
            nextEraseSample = nextBakeSample;
            lastErasedCell = 0xFFFF;
            pendingCell = 0xFFFF;
        }
        else
        {
            u8 guard = 12; /* defensive cap: never more than a handful of ops/frame */
            while ((s32)nextBakeSample <= bakeThreshold && guard--)
            {
                u16 bIdx = nextBakeSample % TRAILSIZE;
                u16 bx = (u16)trailX[bIdx];
                u16 by = (u16)trailY[bIdx];
                u16 cell = (by >> 3) * 32 + (bx >> 3);
                u8 localX = (u8)(bx & 7);
                u8 localY = (u8)(by & 7);

                if (cell != pendingCell)
                {
                    u8 entryForNext;
                    if (pendingCell != 0xFFFF)
                    {
                        u8 d = axisDir(pendingCell, cell);
                        if (d != 0xFF)
                            entryForNext = bakeSimpleCrossing(pendingCell, pendingEntryPoint, cell, d, localX, localY);
                        else
                            entryForNext = bakeDiagonalCrossing(pendingCell, pendingEntryPoint, cell,
                                                                 prevBakeX, prevBakeY, bx, by);
                    }
                    else
                    {
                        entryForNext = bakeFirstCell(localX, localY);
                    }
                    pendingCell = cell;
                    pendingEntryPoint = entryForNext;
                }
                prevBakeX = bx;
                prevBakeY = by;

                nextBakeSample += BAKE_STEP;
            }

            guard = 12;
            while ((s32)nextEraseSample <= eraseThreshold && guard--)
            {
                u16 eIdx = nextEraseSample % TRAILSIZE;
                u16 ex = (u16)trailX[eIdx];
                u16 ey = (u16)trailY[eIdx];
                u16 cell = (ey >> 3) * 32 + (ex >> 3);
                if (cell != lastErasedCell)
                {
                    blockmap[cell] = TILE_BLANK;
                    if (dirtyCount < MAX_DIRTY)
                        dirtyCell[dirtyCount++] = cell;
                    lastErasedCell = cell;
                }
                nextEraseSample += BAKE_STEP;
            }
        }
    }

    /* cheap abs-based self collision against the sprite-rendered window,
       sampling every other segment. Never look further back than the snake
       has actually been alive for, or we'd read the trail buffer's initial
       spawn-point stub data and get a false "collision" near the start of
       a life. */
    {
        u16 maxCheck = curLen;
        u16 ageLimit = snakeAge / SEG_SPACING;
        if (ageLimit < maxCheck)
            maxCheck = ageLimit;
        if (maxCheck > SPRITE_WINDOW)
            maxCheck = SPRITE_WINDOW;

        for (i = SELF_SKIP; i < maxCheck; i += 2)
        {
            u16 tIdx = (headIdx + TRAILSIZE - (u16)(i * SEG_SPACING)) % TRAILSIZE;
            s16 adx = hx - trailX[tIdx];
            s16 ady = hy - trailY[tIdx];
            if (adx < 0) adx = -adx;
            if (ady < 0) ady = -ady;
            if (adx < SELF_R && ady < SELF_R)
                return 1; /* self collision */
        }
    }

    /* collision against the older, permanently-baked tail: O(1) BG lookup.
       Every body-connector tile generated by gen_tiles.py occupies one
       contiguous block of tile indices starting at TILE_BODY_BASE, so
       "is this cell solid" is a single range check regardless of which
       of the many connector shapes it happens to be. */
    if (curLen > SPRITE_WINDOW)
    {
        u16 cell = (hy >> 3) * 32 + (hx >> 3);
        u16 t = blockmap[cell] & 0x3FF; /* mask off flip bits */
        if (t >= TILE_BODY_BASE && t < TILE_BODY_BASE + TILE_BODY_COUNT)
            return 1;
    }

    {
        s16 adx = (s16)hx - (s16)pizzaX;
        s16 ady = (s16)hy - (s16)pizzaY;
        u8 r = pizzaBig ? (PIZZA_R + 4) : PIZZA_R;
        if (adx < 0) adx = -adx;
        if (ady < 0) ady = -ady;
        if (adx < r && ady < r)
        {
            score += pizzaValue;
            curLen += pizzaValue / 3;
            if (curLen > MAX_LEN)
                curLen = MAX_LEN;
            hudDirty = 1;
            spawnPizza();
        }
    }

    return 0;
}

//---------------------------------------------------------------------------------
u8 qualifiesForHighScore(void)
{
    return (score > 0 && score > hsScore[NUM_SCORES - 1]);
}

//---------------------------------------------------------------------------------
void insertHighScore(u16 s, const char *name)
{
    s8 slot, i;
    slot = -1;
    for (i = 0; i < NUM_SCORES; i++)
    {
        if (s > hsScore[i])
        {
            slot = i;
            break;
        }
    }
    if (slot < 0)
        return;
    for (i = NUM_SCORES - 1; i > slot; i--)
    {
        hsScore[i] = hsScore[i - 1];
        hsName[i][0] = hsName[i - 1][0];
        hsName[i][1] = hsName[i - 1][1];
        hsName[i][2] = hsName[i - 1][2];
        hsName[i][3] = hsName[i - 1][3];
    }
    hsScore[slot] = s;
    hsName[slot][0] = name[0];
    hsName[slot][1] = name[1];
    hsName[slot][2] = name[2];
    hsName[slot][3] = 0;
}

//---------------------------------------------------------------------------------
void drawNameRow(u16 row, u8 blinkOn)
{
    u8 i;
    for (i = 0; i < NAME_LEN; i++)
    {
        if (i == nameCursor && !blinkOn)
            blockmap[row * 32 + 14 + i] = TILE_BLANK;
        else
            blockmap[row * 32 + 14 + i] = asciiTile[(u8)('A' + nameLetters[i])];
    }
}

//---------------------------------------------------------------------------------
void nameEntryScreen(void)
{
    u16 padOld = 0;
    u16 frameCount = 0;
    u16 pressed;
    u8 i;

    for (i = 0; i < NAME_LEN; i++)
        nameLetters[i] = 0;
    nameCursor = 0;

    drawWalls();
    writeText(6, 11, "NEW HIGH SCORE");
    writeText(9, 13, "SCORE");
    writeNum(15, 13, score, 6);
    writeText(7, 17, "ENTER YOUR NAME");
    writeText(9, 21, "LEFT RIGHT PICK");
    writeText(6, 22, "UP DOWN CHANGE LETTER");

    for (;;)
    {
        pad0 = padsCurrent(0);
        pressed = pad0 & (u16)(~padOld);

        if (pressed & KEY_LEFT)
            nameCursor = (nameCursor == 0) ? 0 : nameCursor - 1;
        if (pressed & KEY_RIGHT)
            nameCursor = (nameCursor >= NAME_LEN - 1) ? nameCursor : nameCursor + 1;
        if (pressed & KEY_UP)
            nameLetters[nameCursor] = (nameLetters[nameCursor] + 25) % 26;
        if (pressed & KEY_DOWN)
            nameLetters[nameCursor] = (nameLetters[nameCursor] + 1) % 26;
        padOld = pad0;

        drawNameRow(19, (frameCount >> 4) & 1);

        WaitForVBlank();
        dmaCopyVram((u8 *)blockmap, 0x0000, 0x800);
        frameCount++;

        if (pressed & KEY_START)
            break;
    }

    for (i = 0; i < NAME_LEN; i++)
        hiName[i] = 'A' + nameLetters[i];
    hiName[NAME_LEN] = 0;

    insertHighScore(score, hiName);
}

//---------------------------------------------------------------------------------
void hiScoresScreen(void)
{
    u8 i;
    drawWalls();
    writeText(11, 3, "HIGH SCORES");
    for (i = 0; i < NUM_SCORES; i++)
    {
        u16 row = 5 + i;
        writeNum(3, row, i + 1, 2);
        if (hsScore[i])
        {
            writeText(7, row, hsName[i]);
            writeNum(16, row, hsScore[i], 6);
        }
    }
    WaitForVBlank();
    dmaCopyVram((u8 *)blockmap, 0x0000, 0x800);
    for (;;)
    {
        pad0 = padsCurrent(0);
        WaitForVBlank();
        if (pad0 & (KEY_START | KEY_B | KEY_A))
            break;
    }
    gameState = ST_TITLE;
}

//---------------------------------------------------------------------------------
void titleScreen(void)
{
    drawWalls();
    writeText(10, 8, "PIZZA SNAKE");
    writeText(8, 12, "PRESS START");
    writeText(3, 14, "PRESS SELECT FOR SCORES");
    if (hsScore[0])
    {
        writeText(7, 18, "HI SCORE");
        writeText(16, 18, hsName[0]);
        writeNum(20, 18, hsScore[0], 6);
    }
    WaitForVBlank();
    dmaCopyVram((u8 *)blockmap, 0x0000, 0x800);
    for (;;)
    {
        pad0 = padsCurrent(0);
        WaitForVBlank();
        if (pad0 & KEY_START)
        {
            resetGame();
            gameState = ST_PLAYING;
            return;
        }
        if (pad0 & KEY_SELECT)
        {
            gameState = ST_HISCORES;
            return;
        }
    }
}

//---------------------------------------------------------------------------------
void gameOverScreen(void)
{
    hideAllSprites();

    if (qualifiesForHighScore())
    {
        nameEntryScreen();
        gameState = ST_TITLE;
        return;
    }

    drawWalls();
    writeText(11, 12, "GAME OVER");
    writeText(9, 15, "SCORE");
    writeNum(15, 15, score, 6);
    writeText(6, 18, "PRESS START");
    WaitForVBlank();
    dmaCopyVram((u8 *)blockmap, 0x0000, 0x800);
    for (;;)
    {
        pad0 = padsCurrent(0);
        WaitForVBlank();
        if (pad0 & KEY_START)
            break;
    }
    gameState = ST_TITLE;
}

//---------------------------------------------------------------------------------
int main(void)
{
    u16 i;

    setBrightness(0);
    WaitForVBlank();

    randSeed = 0xACE1;
    for (i = 0; i < NUM_SCORES; i++)
    {
        hsScore[i] = 0;
        hsName[i][0] = 'A'; hsName[i][1] = 'A'; hsName[i][2] = 'A'; hsName[i][3] = 0;
    }
    hiName[0] = 'A'; hiName[1] = 'A'; hiName[2] = 'A'; hiName[3] = 0;
    gameState = ST_TITLE;

    oamInitGfxSet(&gfxsprites, (&gfxsprites_end - &gfxsprites),
                   &palsprites, (&palsprites_end - &palsprites),
                   0, 0x4000, OBJ_SIZE8_L16);

    dmaCopyVram(&gfxwalls, 0x1000, (&gfxwalls_end - &gfxwalls));
    dmaCopyCGram((u8 *)&palwalls, 0, (&palwalls_end - &palwalls));

    drawWalls();
    WaitForVBlank();
    dmaCopyVram((u8 *)blockmap, 0x0000, 0x800);

    bgSetGfxPtr(0, 0x1000);
    bgSetMapPtr(0, 0x0000, SC_32x32);

    setMode(BG_MODE1, 0);
    bgSetDisable(1);
    bgSetDisable(2);

    hideAllSprites();
    setScreenOn();

    for (;;)
    {
        switch (gameState)
        {
        case ST_TITLE:
            titleScreen();
            break;

        case ST_HISCORES:
            hiScoresScreen();
            break;

        case ST_PLAYING:
            pad0 = padsCurrent(0);
            if (stepSnake())
            {
                gameState = ST_GAMEOVER;
                break;
            }
            if (hudDirty)
                drawHud();
            drawSprites();
            WaitForVBlank();
            if (hudDirty)
            {
                /* HUD text only ever touches row 0 -- 32 cells, 64 bytes */
                dmaCopyVram((u8 *)blockmap, 0x0000, 64);
                hudDirty = 0;
            }
            {
                u8 i;
                for (i = 0; i < dirtyCount; i++)
                    dmaCopyVram((u8 *)&blockmap[dirtyCell[i]], dirtyCell[i], 2);
                dirtyCount = 0;
            }
            break;

        case ST_GAMEOVER:
            gameOverScreen();
            break;
        }
    }
    return 0;
}
